export { DB_PATH, getDb } from "./db/connection.js"
export { initDb } from "./db/init.js"
export type { CharacterBase, GenerationParams, LLMConnector, SettingsState } from "./db/types.js"
export {
  createCharacter,
  getCharacter,
  listCharacters,
  listStoryCharacterRefs,
  type CharacterRow,
} from "./db/characters.js"
export {
  upsertCharacterCard,
  getCharacterCard,
  getCharacterCardSummary,
  type CharacterCardRow,
  type CharacterCardSummary,
  type CharacterCardFormat,
} from "./db/character-cards.js"
export {
  listStories,
  listStoriesWithCharacters,
  listStoriesWithNpcs,
  getStory,
  createStory,
  updateStory,
  updateStoryMeta,
  deleteStory,
  type StoryRow,
  type StoryCharacterRow,
  type StoryNpcRow,
} from "./db/stories.js"
export {
  getTurnsForStory,
  getTurn,
  getTurnByRequestId,
  getLastTurnForStory,
  getNextTurnNumber,
  createTurn,
  updateTurn,
  updateTurnSnapshot,
  deleteTurn,
  listTurnVariants,
  getTurnVariant,
  createTurnVariant,
  setActiveTurnVariant,
  saveCanceledTurn,
  getCanceledTurn,
  clearCanceledTurn,
  type TurnRow,
  type TurnVariantRow,
  type CanceledTurnPayload,
  type CanceledTurnVariantPayload,
} from "./db/turns.js"
export {
  createChat,
  listChats,
  getChat,
  updateChat,
  deleteChat,
  listChatMembers,
  listChatMessages,
  getChatMessage,
  updateChatMessage,
  deleteChatMessage,
  updateChatNextSpeaker,
  getNextChatMessageIndex,
  appendChatMessage,
  advanceChatSpeaker,
  setCanceledChatExchange,
  getCanceledChatExchange,
  clearCanceledChatExchange,
  type ChatMemberState,
  type ChatRow,
  type ChatMemberRow,
  type ChatMessageRow,
  type ChatMemberInput,
  type CanceledChatExchangePayload,
} from "./db/chats.js"
export { getSettings, updateSettings } from "./db/settings.js"
export {
  listSamplerPresets,
  upsertSamplerPreset,
  deleteSamplerPreset,
  type SamplerPreset,
  type SamplerPresetRow,
} from "./db/presets.js"
