export const INTERNAL_UPSTREAM_FETCH_TIMEOUT_MS = 15_000
export const INTERNAL_STREAM_SESSION_TTL_MS = 45_000
export const INTERNAL_MODELS_CACHE_TTL_MS = 5 * 60 * 1000
export const INTERNAL_SUPPORTED_PARAMS_CACHE_TTL_MS = 5 * 60 * 1000
export const INTERNAL_CTX_LIMIT_CACHE_TTL_MS = 5 * 60 * 1000

export const INTERNAL_PENDING_REQUEST_TTL_MS = 10 * 60 * 1000

export const INTERNAL_UI_ERROR_TOAST_MS = 4000
export const INTERNAL_UI_QUIET_NOTICE_MS = 3500
export const INTERNAL_UI_FLASH_MS = 900
export const INTERNAL_UI_KEYBOARD_SCROLL_DELAY_MS = 120
export const INTERNAL_UI_RESUME_PENDING_TURN_DELAY_MS = 500
