name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew

    - name: Build Unsigned Release APK
      # Uses assembleRelease for optimization. 
      # Added --no-daemon and --parallel to optimize CI memory and build speed.
      run: ./android/gradlew -p android :app:assembleRelease --no-daemon --parallel

    - name: Publish APK (upload artifact)
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned-apk
        # The path changes for release builds. Using a wildcard catches the unsigned apk.
        path: android/app/build/outputs/apk/release/*.apk
        # Optional: Set retention days to save GitHub storage space
        retention-days: 14
